import { readFileSync, existsSync, mkdirSync } from 'fs';
import { dirname } from 'path';
import initSqlJs from 'sql.js';
import { initDataDir, getDBPath } from '../config.mjs';
import { initDB, insertError, getError, getAllErrors, getTopRules, searchErrors, incrementCount, getHotTopics, incrementRefHit, insertCapture, upsertCapture, resolveCapture, getCapturesByCode, getRecentCaptures, getUnresolvedCaptures, getLatestUnresolvedByCode, insertWarning, getWarningsBySnapshot, getLatestSnapshots, createSession, getSessionStats, getStubbornErrors, getFixRate, CAPTURES_DDL } from './schema.mjs';
import { collectErrorFiles, parseErrorFile } from './parser.mjs';

let _db = null;
let _dbPath = null;

// ── Session management ──
// session_id is auto-generated by specmate internally, completely transparent to Agent
let _currentSessionId = null;

/** Return the current session_id, or null if no session has been created yet. */
export function getSessionId() {
    return _currentSessionId;
}

/**
 * Lazily create a session for the current MCP connection lifecycle.
 * Idempotent — returns the existing session_id if already created.
 * @param {string|null} taskName — optional human-readable label (Agent may pass via specmate_scan)
 * @returns {Promise<string>} session_id
 */
export async function ensureSession(taskName = null) {
    if (_currentSessionId) return _currentSessionId;

    const db = await ensureDB();
    const now = new Date();
    const y = String(now.getFullYear());
    const m = String(now.getMonth() + 1).padStart(2, '0');
    const d = String(now.getDate()).padStart(2, '0');
    const h = String(now.getHours()).padStart(2, '0');
    const mi = String(now.getMinutes()).padStart(2, '0');
    const s = String(now.getSeconds()).padStart(2, '0');
    const rand = Math.random().toString(36).substring(2, 6);
    const id = `${y}${m}${d}-${h}${mi}${s}-${rand}`;

    const startedAt = now.toISOString();
    createSession(db, { id, task_name: taskName, started_at: startedAt });
    await saveDB();
    // Only mark session as established after successful DB write.
    // If saveDB() throws, _currentSessionId stays null so the next call will retry.
    _currentSessionId = id;
    return _currentSessionId;
}

async function autoSeedIfEmpty(db) {
    const result = db.exec('SELECT COUNT(*) as cnt FROM errors');
    const count = result.length > 0 ? result[0].values[0][0] : 0;
    if (count > 0) return 0;

    const errorPaths = collectErrorFiles();
    if (errorPaths.length === 0) return 0;

    let inserted = 0;
    for (const filePath of errorPaths.sort()) {
        const content = readFileSync(filePath, 'utf-8');
        const err = parseErrorFile(content);
        if (err.code) {
            insertError(db, err);
            console.log(`  [auto-seed] + ${err.code}: ${err.title}`);
            inserted++;
        }
    }
    return inserted;
}

export async function ensureDB() {
    if (_db) return _db;

    const { created } = initDataDir();
    _dbPath = getDBPath();
    const SQL = await initSqlJs();

    if (existsSync(_dbPath)) {
        const buf = readFileSync(_dbPath);
        _db = new SQL.Database(buf);
        // Ensure new tables and columns exist (migration for existing DBs)
        // New tables (idempotent)
        _db.run(CAPTURES_DDL);
        _db.run(`CREATE INDEX IF NOT EXISTS idx_captures_dedup ON captures(code, file, session_id)`);
        _db.run(`CREATE TABLE IF NOT EXISTS sessions (
            id              TEXT PRIMARY KEY,
            task_name       TEXT,
            started_at      TEXT NOT NULL,
            ended_at        TEXT,
            compile_attempts INTEGER DEFAULT 0,
            compile_failures INTEGER DEFAULT 0
        )`);
        // Add new columns to existing captures table (ignore errors if already exist)
        const migrateCols = [
            "ALTER TABLE captures ADD COLUMN file TEXT",
            "ALTER TABLE captures ADD COLUMN source TEXT DEFAULT 'bsc'",
            "ALTER TABLE captures ADD COLUMN session_id TEXT",
            "ALTER TABLE captures ADD COLUMN repeat_count INTEGER DEFAULT 1",
        ];
        for (const sql of migrateCols) {
            try { _db.run(sql); } catch (_) { /* column already exists */ }
        }
        _db.run(`CREATE TABLE IF NOT EXISTS warnings (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            snapshot_id TEXT NOT NULL,
            timestamp   TEXT NOT NULL,
            file        TEXT NOT NULL,
            line        INTEGER,
            code        TEXT NOT NULL,
            message     TEXT NOT NULL,
            UNIQUE(snapshot_id, file, line, code)
        )`);
        // Ensure errors table exists (old DBs may not have it — missing from earlier migration)
        _db.run(`CREATE TABLE IF NOT EXISTS errors (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            code        TEXT NOT NULL UNIQUE,
            title       TEXT NOT NULL,
            keywords    TEXT NOT NULL,
            phenomena   TEXT NOT NULL,
            cause       TEXT NOT NULL,
            solution    TEXT NOT NULL,
            rules       TEXT,
            count       INTEGER DEFAULT 1
        )`);
        // Auto-seed errors table if empty (e.g. migrated from old schema)
        const seeded = await autoSeedIfEmpty(_db);
        if (seeded > 0) {
            await saveDB();
        }
    } else {
        if (!existsSync(dirname(_dbPath))) {
            mkdirSync(dirname(_dbPath), { recursive: true });
        }
        _db = new SQL.Database();
        initDB(_db);
        // Auto-seed errors table from Markdown source
        await autoSeedIfEmpty(_db);
        await saveDB();
    }
    return _db;
}

async function saveDB() {
    if (!_db || !_dbPath) return;
    const data = _db.export();
    const { writeFileSync } = await import('fs');
    writeFileSync(_dbPath, Buffer.from(data));
}

export async function queryError(code) {
    const db = await ensureDB();
    return getError(db, code);
}

export async function queryAllErrors() {
    const db = await ensureDB();
    return getAllErrors(db);
}

export async function querySearch(keyword) {
    const db = await ensureDB();
    return searchErrors(db, keyword);
}

export async function hitError(code) {
    const db = await ensureDB();
    incrementCount(db, code);
    await saveDB();
}

export async function queryTopRules(limit) {
    const db = await ensureDB();
    return getTopRules(db, limit);
}

export async function queryHotTopics(limit = 5) {
    const db = await ensureDB();
    return getHotTopics(db, limit);
}

export async function trackRefHit(topic) {
    const db = await ensureDB();
    incrementRefHit(db, topic);
    await saveDB();
}

export async function addCapture({ code, bsc_output, files, file = null, source = 'bsc', session_id = null, cause = null }) {
    const db = await ensureDB();
    const timestamp = new Date().toISOString();
    const sid = session_id || _currentSessionId;
    const result = upsertCapture(db, { code, timestamp, bsc_output, files, file, source, session_id: sid, cause, status: 'unresolved' });
    await saveDB();
    return result;
}

export async function resolveCaptureById(id, { cause, solution }) {
    const db = await ensureDB();
    resolveCapture(db, id, { cause, solution });
    await saveDB();
}

export async function queryCapturesByCode(code, limit = 5) {
    const db = await ensureDB();
    return getCapturesByCode(db, code, limit);
}

export async function queryRecentCaptures(limit = 10) {
    const db = await ensureDB();
    return getRecentCaptures(db, limit);
}

export async function queryUnresolvedCaptures() {
    const db = await ensureDB();
    return getUnresolvedCaptures(db);
}

export async function getLatestCaptureByCode(code) {
    const db = await ensureDB();
    return getLatestUnresolvedByCode(db, code);
}

export async function saveWarningSnapshot(snapshot_id, warnings) {
    const db = await ensureDB();
    const timestamp = new Date().toISOString();
    for (const w of warnings) {
        insertWarning(db, {
            snapshot_id,
            timestamp,
            file: w.file,
            line: w.line || null,
            code: w.code,
            message: w.message,
        });
    }
    await saveDB();
}

export async function getLatestSnapshotId() {
    const db = await ensureDB();
    const snapshots = getLatestSnapshots(db, 1);
    return snapshots.length > 0 ? snapshots[0].snapshot_id : null;
}

export async function queryLatestSnapshots(limit = 2) {
    const db = await ensureDB();
    return getLatestSnapshots(db, limit);
}

export async function diffWarnings(snapshot_a, snapshot_b) {
    const db = await ensureDB();
    const prevWarnings = getWarningsBySnapshot(db, snapshot_a);
    const currWarnings = getWarningsBySnapshot(db, snapshot_b);

    const key = w => `${w.file}:${w.line}:${w.code}`;
    const prevKeys = new Set(prevWarnings.map(key));
    const currKeys = new Set(currWarnings.map(key));

    return {
        added: currWarnings.filter(w => !prevKeys.has(key(w))),
        removed: prevWarnings.filter(w => !currKeys.has(key(w))),
        persistent: currWarnings.filter(w => prevKeys.has(key(w))),
    };
}

// ── P1 statistics: session-level aggregation queries ──

/**
 * Get compile attempts and unresolved error count for the current session.
 * @param {string} sessionId
 * @returns {Promise<{ compileAttempts: number, unresolvedCount: number }>}
 */
export async function querySessionStats(sessionId) {
    const db = await ensureDB();
    return getSessionStats(db, sessionId);
}

/**
 * Get stubborn errors (repeat_count >= minCount) for the current session.
 * @param {string} sessionId
 * @param {number} minCount - minimum repeat_count (default 2)
 * @returns {Promise<Array<{ code: string, file: string, repeat_count: number }>>}
 */
export async function queryStubbornErrors(sessionId, minCount = 2) {
    const db = await ensureDB();
    return getStubbornErrors(db, sessionId, minCount);
}

/**
 * Get fix rate (resolved vs total captures) for the current session.
 * @param {string} sessionId
 * @returns {Promise<{ resolved: number, total: number }>}
 */
export async function queryFixRate(sessionId) {
    const db = await ensureDB();
    return getFixRate(db, sessionId);
}

export function closeDB() {
    if (_db) {
        _db.close();
        _db = null;
    }
}
