import { readFileSync, existsSync, mkdirSync } from 'fs';
import { dirname } from 'path';
import initSqlJs from 'sql.js';
import { initDataDir, getDBPath } from '../config.mjs';
import { initDB, insertError, getError, getAllErrors, getTopRules, searchErrors, incrementCount, getHotTopics, incrementRefHit, insertCapture, upsertCapture, resolveCapture, getCapturesByCode, getRecentCaptures, getUnresolvedCaptures, getLatestUnresolvedByCode, insertWarning, getWarningsBySnapshot, getLatestSnapshots, createSession, endSession, getSessionStats, getStubbornErrors, getFixRate, getErrorCodeStats, getTopErrorCodes, getUnresolvedCount, getClusteredCaptures, setCaptureReviewStatus, getAllCapturesByCode, CAPTURES_DDL } from './schema.mjs';
import { collectErrorFiles, parseErrorFile } from './parser.mjs';

let _db = null;
let _dbPath = null;

// ── Session management ──
// session_id is auto-generated by specmate internally, completely transparent to Agent
let _currentSessionId = null;

/** Return the current session_id, or null if no session has been created yet. */
export function getSessionId() {
    return _currentSessionId;
}

/**
 * Lazily create a session for the current MCP connection lifecycle.
 * Idempotent — returns the existing session_id if already created.
 * @param {string|null} taskName — optional human-readable label (Agent may pass via specmate_scan)
 * @returns {Promise<string>} session_id
 */
export async function ensureSession(taskName = null) {
    if (_currentSessionId) return _currentSessionId;

    const db = await ensureDB();
    const now = new Date();
    const y = String(now.getFullYear());
    const m = String(now.getMonth() + 1).padStart(2, '0');
    const d = String(now.getDate()).padStart(2, '0');
    const h = String(now.getHours()).padStart(2, '0');
    const mi = String(now.getMinutes()).padStart(2, '0');
    const s = String(now.getSeconds()).padStart(2, '0');
    const rand = Math.random().toString(36).substring(2, 6);
    const id = `${y}${m}${d}-${h}${mi}${s}-${rand}`;

    const startedAt = now.toISOString();
    createSession(db, { id, task_name: taskName, started_at: startedAt });
    await saveDB();
    // Only mark session as established after successful DB write.
    // If saveDB() throws, _currentSessionId stays null so the next call will retry.
    _currentSessionId = id;
    return _currentSessionId;
}

/**
 * End the current session — mark ended_at in the sessions table.
 * Called on MCP server shutdown. Idempotent.
 */
export async function endCurrentSession() {
    if (!_currentSessionId) return;
    const db = await ensureDB();
    endSession(db, _currentSessionId);
    await saveDB();
}

const MAX_SEED_FILES = 100;

async function autoSeedIfEmpty(db) {
    const result = db.exec('SELECT COUNT(*) as cnt FROM errors');
    const count = result.length > 0 ? result[0].values[0][0] : 0;
    if (count > 0) return 0;

    const errorPaths = collectErrorFiles();
    if (errorPaths.length === 0) return 0;

    if (errorPaths.length > MAX_SEED_FILES) {
        console.warn(`  [auto-seed] WARNING: ${errorPaths.length} files found, limiting to first ${MAX_SEED_FILES}`);
    }

    let inserted = 0;
    for (const filePath of errorPaths.sort().slice(0, MAX_SEED_FILES)) {
        const content = readFileSync(filePath, 'utf-8');
        const err = parseErrorFile(content);
        if (err.code) {
            insertError(db, err);
            console.log(`  [auto-seed] + ${err.code}: ${err.title}`);
            inserted++;
        }
    }
    return inserted;
}

export async function ensureDB() {
    if (_db) return _db;

    const { created } = initDataDir();
    _dbPath = getDBPath();
    const SQL = await initSqlJs();

    if (existsSync(_dbPath)) {
        const buf = readFileSync(_dbPath);
        const db = new SQL.Database(buf);
        // Ensure new tables and columns exist (migration for existing DBs)
        // New tables (idempotent)
        db.run(CAPTURES_DDL);
        db.run(`CREATE TABLE IF NOT EXISTS sessions (
            id              TEXT PRIMARY KEY,
            task_name       TEXT,
            started_at      TEXT NOT NULL,
            ended_at        TEXT,
            compile_attempts INTEGER DEFAULT 0,
            compile_failures INTEGER DEFAULT 0
        )`);
        // Add new columns to existing captures table (ignore errors if already exist)
        // MUST run BEFORE creating the dedup index, because the index references
        // file and session_id columns that may not exist yet in old databases.
        const migrateCols = [
            "ALTER TABLE captures ADD COLUMN file TEXT",
            "ALTER TABLE captures ADD COLUMN source TEXT DEFAULT 'bsc'",
            "ALTER TABLE captures ADD COLUMN session_id TEXT",
            "ALTER TABLE captures ADD COLUMN error_token TEXT",
            "ALTER TABLE captures ADD COLUMN repeat_count INTEGER DEFAULT 1",
            "ALTER TABLE captures ADD COLUMN cause TEXT",
            "ALTER TABLE captures ADD COLUMN solution TEXT",
            // ── Phase 1: review status fields ──
            "ALTER TABLE captures ADD COLUMN review_status TEXT DEFAULT 'unreviewed'",
            "ALTER TABLE captures ADD COLUMN reviewed_at TEXT",
        ];
        for (const sql of migrateCols) {
            try { db.run(sql); } catch (_) { /* column already exists */ }
        }
        // Index must come AFTER ALTER TABLE — otherwise it fails referencing
        // non-existent columns in old databases.
        try {
            db.run(`CREATE INDEX IF NOT EXISTS idx_captures_dedup ON captures(code, file, session_id)`);
        } catch (_) { /* index creation failed (e.g. columns still missing) */ }
        try {
            db.run(`CREATE INDEX IF NOT EXISTS idx_captures_token ON captures(error_token, code)`);
        } catch (_) { /* index creation failed */ }
        db.run(`CREATE TABLE IF NOT EXISTS warnings (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            snapshot_id TEXT NOT NULL,
            timestamp   TEXT NOT NULL,
            file        TEXT NOT NULL,
            line        INTEGER,
            code        TEXT NOT NULL,
            message     TEXT NOT NULL,
            UNIQUE(snapshot_id, file, line, code)
        )`);
        // Ensure errors table exists (old DBs may not have it — missing from earlier migration)
        db.run(`CREATE TABLE IF NOT EXISTS errors (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            code        TEXT NOT NULL UNIQUE,
            title       TEXT NOT NULL,
            keywords    TEXT NOT NULL,
            phenomena   TEXT NOT NULL,
            cause       TEXT NOT NULL,
            solution    TEXT NOT NULL,
            rules       TEXT,
            count       INTEGER DEFAULT 1
        )`);
        // Auto-seed errors table if empty (e.g. migrated from old schema)
        const seeded = await autoSeedIfEmpty(db);
        // Only assign to _db after ALL migration steps succeed, so a failed
        // migration doesn't permanently cache a broken database handle.
        _db = db;
        if (seeded > 0) {
            await saveDB();
        }
    } else {
        if (!existsSync(dirname(_dbPath))) {
            mkdirSync(dirname(_dbPath), { recursive: true });
        }
        _db = new SQL.Database();
        initDB(_db);
        // Auto-seed errors table from Markdown source
        await autoSeedIfEmpty(_db);
        await saveDB();
    }
    return _db;
}

async function saveDB() {
    if (!_db || !_dbPath) return;
    const data = _db.export();
    const { writeFileSync } = await import('fs');
    writeFileSync(_dbPath, Buffer.from(data));
}

export async function queryError(code) {
    const db = await ensureDB();
    return getError(db, code);
}

export async function queryAllErrors() {
    const db = await ensureDB();
    return getAllErrors(db);
}

export async function querySearch(keyword) {
    const db = await ensureDB();
    return searchErrors(db, keyword);
}

export async function hitError(code) {
    const db = await ensureDB();
    incrementCount(db, code);
    await saveDB();
}

export async function queryTopRules(limit) {
    const db = await ensureDB();
    return getTopRules(db, limit);
}

export async function queryHotTopics(limit = 5) {
    const db = await ensureDB();
    return getHotTopics(db, limit);
}

export async function trackRefHit(topic) {
    const db = await ensureDB();
    incrementRefHit(db, topic);
    await saveDB();
}

export async function addCapture({ code, bsc_output, files, file = null, source = 'bsc', session_id = null, cause = null }) {
    const db = await ensureDB();
    const timestamp = new Date().toISOString();
    const sid = session_id || _currentSessionId;
    const result = upsertCapture(db, { code, timestamp, bsc_output, files, file, source, session_id: sid, cause, status: 'unresolved' });
    await saveDB();
    return result;
}

/**
 * Batch insert captures — opens DB once, inserts all, saves once.
 * P2-1 fix: replaces O(codes×files) individual addCapture calls.
 */
export async function addCapturesBatch(entries) {
    if (!entries || entries.length === 0) return [];
    const db = await ensureDB();
    const timestamp = new Date().toISOString();
    const sid = _currentSessionId;
    const results = [];
    for (const entry of entries) {
        const result = upsertCapture(db, {
            code: entry.code,
            timestamp,
            bsc_output: entry.bsc_output || '',
            files: entry.files || null,
            file: entry.file || null,
            source: entry.source || 'bsc',
            session_id: entry.session_id || sid,
            cause: entry.cause || null,
            status: 'unresolved',
        });
        results.push(result);
    }
    await saveDB();
    return results;
}

export async function resolveCaptureById(id, { cause, solution }) {
    const db = await ensureDB();
    resolveCapture(db, id, { cause, solution });
    await saveDB();
}

export async function queryCapturesByCode(code, limit = 5) {
    const db = await ensureDB();
    return getCapturesByCode(db, code, limit);
}

export async function queryRecentCaptures(limit = 10) {
    const db = await ensureDB();
    return getRecentCaptures(db, limit);
}

export async function queryUnresolvedCaptures() {
    const db = await ensureDB();
    return getUnresolvedCaptures(db);
}

export async function getLatestCaptureByCode(code) {
    const db = await ensureDB();
    return getLatestUnresolvedByCode(db, code);
}

export async function saveWarningSnapshot(snapshot_id, warnings) {
    const db = await ensureDB();
    const timestamp = new Date().toISOString();
    for (const w of warnings) {
        insertWarning(db, {
            snapshot_id,
            timestamp,
            file: w.file,
            line: w.line || null,
            code: w.code,
            message: w.message,
        });
    }
    await saveDB();
}

export async function getLatestSnapshotId() {
    const db = await ensureDB();
    const snapshots = getLatestSnapshots(db, 1);
    return snapshots.length > 0 ? snapshots[0].snapshot_id : null;
}

export async function queryLatestSnapshots(limit = 2) {
    const db = await ensureDB();
    return getLatestSnapshots(db, limit);
}

export async function diffWarnings(snapshot_a, snapshot_b) {
    const db = await ensureDB();
    const prevWarnings = getWarningsBySnapshot(db, snapshot_a);
    const currWarnings = getWarningsBySnapshot(db, snapshot_b);

    const key = w => `${w.file}:${w.line}:${w.code}`;
    const prevKeys = new Set(prevWarnings.map(key));
    const currKeys = new Set(currWarnings.map(key));

    return {
        added: currWarnings.filter(w => !prevKeys.has(key(w))),
        removed: prevWarnings.filter(w => !currKeys.has(key(w))),
        persistent: currWarnings.filter(w => prevKeys.has(key(w))),
    };
}

// ── P1 statistics: session-level aggregation queries ──

/**
 * Get compile attempts and unresolved error count for the current session.
 * @param {string} sessionId
 * @returns {Promise<{ compileAttempts: number, unresolvedCount: number }>}
 */
export async function querySessionStats(sessionId) {
    const db = await ensureDB();
    return getSessionStats(db, sessionId);
}

/**
 * Get stubborn errors (repeat_count >= minCount) for the current session.
 * @param {string} sessionId
 * @param {number} minCount - minimum repeat_count (default 2)
 * @returns {Promise<Array<{ code: string, file: string, repeat_count: number }>>}
 */
export async function queryStubbornErrors(sessionId, minCount = 2) {
    const db = await ensureDB();
    return getStubbornErrors(db, sessionId, minCount);
}

/**
 * Get fix rate (resolved vs total captures) for the current session.
 * @param {string} sessionId
 * @returns {Promise<{ resolved: number, total: number }>}
 */
export async function queryFixRate(sessionId) {
    const db = await ensureDB();
    return getFixRate(db, sessionId);
}

// ── Cross-session aggregation queries (Phase 0) ──

/**
 * Get total occurrence count and distinct session count for a specific error code.
 * Used by specmate_capture response: "该错误码已累计 N 次（跨 M 个 session）"
 * @param {string} code
 * @returns {Promise<{ totalCount: number, sessionCount: number }>}
 */
export async function queryErrorCodeStats(code) {
    const db = await ensureDB();
    return getErrorCodeStats(db, code);
}

/**
 * Get TOP N most frequently captured error codes (cross-session).
 * Used by specmate_scan history section.
 * @param {number} limit
 * @returns {Promise<Array<{ code: string, total_count: number, session_count: number }>>}
 */
export async function queryTopErrorCodes(limit = 5) {
    const db = await ensureDB();
    return getTopErrorCodes(db, limit);
}

/**
 * Get count of unresolved captures (cross-session).
 * Used by specmate_scan history section.
 * @returns {Promise<number>}
 */
export async function queryUnresolvedCount() {
    const db = await ensureDB();
    return getUnresolvedCount(db);
}

// ── Phase 1: auto-cluster + review CLI ──

/**
 * Get clustered captures for review.
 * Groups unreviewed captures by error code, filtering by minimum repeat count
 * and minimum number of distinct sessions.
 * @param {number} minRepeatCount - minimum total repeat_count (default 3)
 * @param {number} minSessions - minimum distinct sessions (default 2)
 * @returns {Promise<Array<{ code, total_repeat, session_count, files, samples, latest_cause, latest_solution }>>}
 */
export async function queryClusteredCaptures(minRepeatCount = 3, minSessions = 2) {
    const db = await ensureDB();
    return getClusteredCaptures(db, minRepeatCount, minSessions);
}

/**
 * Approve captures for a given error code: mark all captures as 'approved'
 * and return the aggregated capture data for doc generation.
 * @param {string} code - error code to approve
 * @returns {Promise<{ updated: number, captures: Array<object> }>}
 */
export async function approveCapturesByCode(code) {
    const db = await ensureDB();
    const captures = getAllCapturesByCode(db, code);
    const updated = setCaptureReviewStatus(db, code, 'approved');
    await saveDB();
    return { updated, captures };
}

/**
 * Reject captures for a given error code: mark all captures as 'rejected'.
 * @param {string} code - error code to reject
 * @returns {Promise<number>} number of rows updated
 */
export async function rejectCapturesByCode(code) {
    const db = await ensureDB();
    const updated = setCaptureReviewStatus(db, code, 'rejected');
    await saveDB();
    return updated;
}

/**
 * Get all captures for a specific error code (any review_status).
 * @param {string} code
 * @returns {Promise<Array<object>>}
 */
export async function queryAllCapturesByCode(code) {
    const db = await ensureDB();
    return getAllCapturesByCode(db, code);
}

export function closeDB() {
    if (_db) {
        _db.close();
        _db = null;
    }
}
