//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e)
//
// On Sat Jul 18 12:00:02 CST 2026
//
//
// Ports:
// Name                         I/O  size props
// io_data_in                     O     1 const
// RDY_io_data_in                 O     1 const
// io_data_out                    O     1 reg
// RDY_io_data_out                O     1 const
// io_oe                          O     1 reg
// RDY_io_oe                      O     1 const
// get_value                      O     1 reg
// RDY_get_value                  O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTrapGpio2(CLK,
		   RST_N,

		   io_data_in,
		   RDY_io_data_in,

		   io_data_out,
		   RDY_io_data_out,

		   io_oe,
		   RDY_io_oe,

		   get_value,
		   RDY_get_value);
  input  CLK;
  input  RST_N;

  // value method io_data_in
  output io_data_in;
  output RDY_io_data_in;

  // value method io_data_out
  output io_data_out;
  output RDY_io_data_out;

  // value method io_oe
  output io_oe;
  output RDY_io_oe;

  // value method get_value
  output get_value;
  output RDY_get_value;

  // signals for module outputs
  wire RDY_get_value,
       RDY_io_data_in,
       RDY_io_data_out,
       RDY_io_oe,
       get_value,
       io_data_in,
       io_data_out,
       io_oe;

  // register count
  reg [3 : 0] count;
  wire [3 : 0] count$D_IN;
  wire count$EN;

  // register oe_reg
  reg oe_reg;
  wire oe_reg$D_IN, oe_reg$EN;

  // register out_val
  reg out_val;
  wire out_val$D_IN, out_val$EN;

  // value method io_data_in
  assign io_data_in = 1'd0 ;
  assign RDY_io_data_in = 1'd1 ;

  // value method io_data_out
  assign io_data_out = out_val ;
  assign RDY_io_data_out = 1'd1 ;

  // value method io_oe
  assign io_oe = oe_reg ;
  assign RDY_io_oe = 1'd1 ;

  // value method get_value
  assign get_value = out_val ;
  assign RDY_get_value = 1'd1 ;

  // register count
  assign count$D_IN = count + 4'd1 ;
  assign count$EN = 1'd1 ;

  // register oe_reg
  assign oe_reg$D_IN = ~oe_reg ;
  assign oe_reg$EN = count == 4'd5 ;

  // register out_val
  assign out_val$D_IN = ~out_val ;
  assign out_val$EN = oe_reg ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        count <= `BSV_ASSIGNMENT_DELAY 4'd0;
	oe_reg <= `BSV_ASSIGNMENT_DELAY 1'd0;
	out_val <= `BSV_ASSIGNMENT_DELAY 1'd0;
      end
    else
      begin
        if (count$EN) count <= `BSV_ASSIGNMENT_DELAY count$D_IN;
	if (oe_reg$EN) oe_reg <= `BSV_ASSIGNMENT_DELAY oe_reg$D_IN;
	if (out_val$EN) out_val <= `BSV_ASSIGNMENT_DELAY out_val$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    count = 4'hA;
    oe_reg = 1'h0;
    out_val = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkTrapGpio2

