//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e)
//
// On Sat Jul 18 12:00:03 CST 2026
//
//
// Ports:
// Name                         I/O  size props
// get_tick                       O     1 reg
// RDY_get_tick                   O     1 const
// get_tx                         O     1 reg
// RDY_get_tx                     O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTrapUart1(CLK,
		   RST_N,

		   get_tick,
		   RDY_get_tick,

		   get_tx,
		   RDY_get_tx);
  input  CLK;
  input  RST_N;

  // value method get_tick
  output get_tick;
  output RDY_get_tick;

  // value method get_tx
  output get_tx;
  output RDY_get_tx;

  // signals for module outputs
  wire RDY_get_tick, RDY_get_tx, get_tick, get_tx;

  // register baud_cnt
  reg [8 : 0] baud_cnt;
  wire [8 : 0] baud_cnt$D_IN;
  wire baud_cnt$EN;

  // register bit_idx
  reg [2 : 0] bit_idx;
  wire [2 : 0] bit_idx$D_IN;
  wire bit_idx$EN;

  // register tick
  reg tick;
  wire tick$D_IN, tick$EN;

  // register tx
  reg tx;
  wire tx$D_IN, tx$EN;

  // register tx_data
  reg [7 : 0] tx_data;
  wire [7 : 0] tx_data$D_IN;
  wire tx_data$EN;

  // remaining internal signals
  wire [8 : 0] x__h247;

  // value method get_tick
  assign get_tick = tick ;
  assign RDY_get_tick = 1'd1 ;

  // value method get_tx
  assign get_tx = tx ;
  assign RDY_get_tx = 1'd1 ;

  // register baud_cnt
  assign baud_cnt$D_IN = (baud_cnt == 9'd433) ? 9'd0 : x__h247 ;
  assign baud_cnt$EN = 1'd1 ;

  // register bit_idx
  assign bit_idx$D_IN = 3'h0 ;
  assign bit_idx$EN = 1'b0 ;

  // register tick
  assign tick$D_IN = baud_cnt == 9'd433 ;
  assign tick$EN = 1'd1 ;

  // register tx
  assign tx$D_IN = 1'b0 ;
  assign tx$EN = 1'b0 ;

  // register tx_data
  assign tx_data$D_IN = 8'h0 ;
  assign tx_data$EN = 1'b0 ;

  // remaining internal signals
  assign x__h247 = baud_cnt + 9'd1 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        baud_cnt <= `BSV_ASSIGNMENT_DELAY 9'd0;
	bit_idx <= `BSV_ASSIGNMENT_DELAY 3'd0;
	tick <= `BSV_ASSIGNMENT_DELAY 1'd0;
	tx <= `BSV_ASSIGNMENT_DELAY 1'd1;
	tx_data <= `BSV_ASSIGNMENT_DELAY 8'h55;
      end
    else
      begin
        if (baud_cnt$EN) baud_cnt <= `BSV_ASSIGNMENT_DELAY baud_cnt$D_IN;
	if (bit_idx$EN) bit_idx <= `BSV_ASSIGNMENT_DELAY bit_idx$D_IN;
	if (tick$EN) tick <= `BSV_ASSIGNMENT_DELAY tick$D_IN;
	if (tx$EN) tx <= `BSV_ASSIGNMENT_DELAY tx$D_IN;
	if (tx_data$EN) tx_data <= `BSV_ASSIGNMENT_DELAY tx_data$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    baud_cnt = 9'h0AA;
    bit_idx = 3'h2;
    tick = 1'h0;
    tx = 1'h0;
    tx_data = 8'hAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkTrapUart1

