//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e)
//
// On Sat Jul 18 12:06:02 CST 2026
//
//
// Ports:
// Name                         I/O  size props
// get_result                     O     8 reg
// RDY_get_result                 O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTrapArbiter1(CLK,
		      RST_N,

		      get_result,
		      RDY_get_result);
  input  CLK;
  input  RST_N;

  // value method get_result
  output [7 : 0] get_result;
  output RDY_get_result;

  // signals for module outputs
  wire [7 : 0] get_result;
  wire RDY_get_result;

  // register addr
  reg [3 : 0] addr;
  wire [3 : 0] addr$D_IN;
  wire addr$EN;

  // register init_idx
  reg [3 : 0] init_idx;
  wire [3 : 0] init_idx$D_IN;
  wire init_idx$EN;

  // register inited
  reg inited;
  wire inited$D_IN, inited$EN;

  // register result
  reg [7 : 0] result;
  wire [7 : 0] result$D_IN;
  wire result$EN;

  // ports of submodule rf
  wire [7 : 0] rf$D_IN, rf$D_OUT_1, rf$D_OUT_2, rf$D_OUT_3;
  wire [3 : 0] rf$ADDR_1,
	       rf$ADDR_2,
	       rf$ADDR_3,
	       rf$ADDR_4,
	       rf$ADDR_5,
	       rf$ADDR_IN;
  wire rf$WE;

  // remaining internal signals
  wire [7 : 0] x__h449;

  // value method get_result
  assign get_result = result ;
  assign RDY_get_result = 1'd1 ;

  // submodule rf
  RegFile #(.addr_width(32'd4),
	    .data_width(32'd8),
	    .lo(4'd0),
	    .hi(4'd15)) rf(.CLK(CLK),
			   .ADDR_1(rf$ADDR_1),
			   .ADDR_2(rf$ADDR_2),
			   .ADDR_3(rf$ADDR_3),
			   .ADDR_4(rf$ADDR_4),
			   .ADDR_5(rf$ADDR_5),
			   .ADDR_IN(rf$ADDR_IN),
			   .D_IN(rf$D_IN),
			   .WE(rf$WE),
			   .D_OUT_1(rf$D_OUT_1),
			   .D_OUT_2(rf$D_OUT_2),
			   .D_OUT_3(rf$D_OUT_3),
			   .D_OUT_4(),
			   .D_OUT_5());

  // register addr
  assign addr$D_IN = addr + 4'd1 ;
  assign addr$EN = inited ;

  // register init_idx
  assign init_idx$D_IN = init_idx + 4'd1 ;
  assign init_idx$EN = !inited && init_idx != 4'd14 ;

  // register inited
  assign inited$D_IN = 1'd1 ;
  assign inited$EN = !inited && init_idx == 4'd14 ;

  // register result
  assign result$D_IN = x__h449 + rf$D_OUT_1 ;
  assign result$EN = inited ;

  // submodule rf
  assign rf$ADDR_1 = addr + 4'd2 ;
  assign rf$ADDR_2 = addr + 4'd1 ;
  assign rf$ADDR_3 = addr ;
  assign rf$ADDR_4 = 4'h0 ;
  assign rf$ADDR_5 = 4'h0 ;
  assign rf$ADDR_IN = init_idx ;
  assign rf$D_IN = { 3'd0, init_idx, 1'd0 } ;
  assign rf$WE = !inited ;

  // remaining internal signals
  assign x__h449 = rf$D_OUT_3 + rf$D_OUT_2 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        addr <= `BSV_ASSIGNMENT_DELAY 4'd0;
	init_idx <= `BSV_ASSIGNMENT_DELAY 4'd0;
	inited <= `BSV_ASSIGNMENT_DELAY 1'd0;
	result <= `BSV_ASSIGNMENT_DELAY 8'd0;
      end
    else
      begin
        if (addr$EN) addr <= `BSV_ASSIGNMENT_DELAY addr$D_IN;
	if (init_idx$EN) init_idx <= `BSV_ASSIGNMENT_DELAY init_idx$D_IN;
	if (inited$EN) inited <= `BSV_ASSIGNMENT_DELAY inited$D_IN;
	if (result$EN) result <= `BSV_ASSIGNMENT_DELAY result$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    addr = 4'hA;
    init_idx = 4'hA;
    inited = 1'h0;
    result = 8'hAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkTrapArbiter1

