//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e)
//
// On Sat Jul 18 11:59:52 CST 2026
//
//
// Ports:
// Name                         I/O  size props
// get_total                      O     8 reg
// RDY_get_total                  O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTrapSchedule1(CLK,
		       RST_N,

		       get_total,
		       RDY_get_total);
  input  CLK;
  input  RST_N;

  // value method get_total
  output [7 : 0] get_total;
  output RDY_get_total;

  // signals for module outputs
  wire [7 : 0] get_total;
  wire RDY_get_total;

  // register cycle
  reg [3 : 0] cycle;
  reg [3 : 0] cycle$D_IN;
  wire cycle$EN;

  // register inc_a
  reg [7 : 0] inc_a;
  wire [7 : 0] inc_a$D_IN;
  wire inc_a$EN;

  // register inc_b
  reg [7 : 0] inc_b;
  wire [7 : 0] inc_b$D_IN;
  wire inc_b$EN;

  // register total
  reg [7 : 0] total;
  reg [7 : 0] total$D_IN;
  wire total$EN;

  // rule scheduling signals
  wire WILL_FIRE_RL_rl_c;

  // inputs to muxes for submodule ports
  wire [7 : 0] MUX_total$write_1__VAL_1, MUX_total$write_1__VAL_2;

  // value method get_total
  assign get_total = total ;
  assign RDY_get_total = 1'd1 ;

  // rule RL_rl_c
  assign WILL_FIRE_RL_rl_c = cycle >= 4'd2 ;

  // inputs to muxes for submodule ports
  assign MUX_total$write_1__VAL_1 = total + inc_a ;
  assign MUX_total$write_1__VAL_2 = total + inc_b ;

  // register cycle
  always@(WILL_FIRE_RL_rl_c or cycle)
  begin
    case (1'b1) // synopsys parallel_case
      WILL_FIRE_RL_rl_c: cycle$D_IN = 4'd0;
      cycle == 4'd0: cycle$D_IN = 4'd1;
      cycle == 4'd1: cycle$D_IN = 4'd2;
      default: cycle$D_IN = 4'b1010 /* unspecified value */ ;
    endcase
  end
  assign cycle$EN = WILL_FIRE_RL_rl_c || cycle == 4'd0 || cycle == 4'd1 ;

  // register inc_a
  assign inc_a$D_IN = inc_a + 8'd1 ;
  assign inc_a$EN = WILL_FIRE_RL_rl_c ;

  // register inc_b
  assign inc_b$D_IN = inc_b + 8'd2 ;
  assign inc_b$EN = WILL_FIRE_RL_rl_c ;

  // register total
  always@(cycle or
	  MUX_total$write_1__VAL_1 or
	  MUX_total$write_1__VAL_2 or WILL_FIRE_RL_rl_c)
  begin
    case (1'b1) // synopsys parallel_case
      cycle == 4'd0: total$D_IN = MUX_total$write_1__VAL_1;
      cycle == 4'd1: total$D_IN = MUX_total$write_1__VAL_2;
      WILL_FIRE_RL_rl_c: total$D_IN = 8'd0;
      default: total$D_IN = 8'b10101010 /* unspecified value */ ;
    endcase
  end
  assign total$EN = cycle == 4'd0 || cycle == 4'd1 || WILL_FIRE_RL_rl_c ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        cycle <= `BSV_ASSIGNMENT_DELAY 4'd0;
	inc_a <= `BSV_ASSIGNMENT_DELAY 8'd0;
	inc_b <= `BSV_ASSIGNMENT_DELAY 8'd0;
	total <= `BSV_ASSIGNMENT_DELAY 8'd0;
      end
    else
      begin
        if (cycle$EN) cycle <= `BSV_ASSIGNMENT_DELAY cycle$D_IN;
	if (inc_a$EN) inc_a <= `BSV_ASSIGNMENT_DELAY inc_a$D_IN;
	if (inc_b$EN) inc_b <= `BSV_ASSIGNMENT_DELAY inc_b$D_IN;
	if (total$EN) total <= `BSV_ASSIGNMENT_DELAY total$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    cycle = 4'hA;
    inc_a = 8'hAA;
    inc_b = 8'hAA;
    total = 8'hAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkTrapSchedule1

