//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e)
//
// On Sat Jul 18 12:10:59 CST 2026
//
//
// Ports:
// Name                         I/O  size props
// get_read_data                  O     8 reg
// RDY_get_read_data              O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTrapBram1(CLK,
		   RST_N,

		   get_read_data,
		   RDY_get_read_data);
  input  CLK;
  input  RST_N;

  // value method get_read_data
  output [7 : 0] get_read_data;
  output RDY_get_read_data;

  // signals for module outputs
  wire [7 : 0] get_read_data;
  wire RDY_get_read_data;

  // inlined wires
  wire [1 : 0] bram_serverAdapter_s1_1$wget,
	       bram_serverAdapter_writeWithResp$wget;
  wire bram_serverAdapter_cnt_1$whas,
       bram_serverAdapter_outData_enqw$whas,
       bram_serverAdapter_writeWithResp$whas;

  // register addr
  reg [7 : 0] addr;
  wire [7 : 0] addr$D_IN;
  wire addr$EN;

  // register bram_serverAdapter_cnt
  reg [2 : 0] bram_serverAdapter_cnt;
  wire [2 : 0] bram_serverAdapter_cnt$D_IN;
  wire bram_serverAdapter_cnt$EN;

  // register bram_serverAdapter_s1
  reg [1 : 0] bram_serverAdapter_s1;
  wire [1 : 0] bram_serverAdapter_s1$D_IN;
  wire bram_serverAdapter_s1$EN;

  // register data
  reg [7 : 0] data;
  wire [7 : 0] data$D_IN;
  wire data$EN;

  // register inited
  reg inited;
  wire inited$D_IN, inited$EN;

  // register result
  reg [7 : 0] result;
  wire [7 : 0] result$D_IN;
  wire result$EN;

  // ports of submodule bram_memory
  wire [7 : 0] bram_memory$ADDR, bram_memory$DI, bram_memory$DO;
  wire bram_memory$EN, bram_memory$WE;

  // ports of submodule bram_serverAdapter_outData_beforeDeq
  wire bram_serverAdapter_outData_beforeDeq$D_IN,
       bram_serverAdapter_outData_beforeDeq$EN,
       bram_serverAdapter_outData_beforeDeq$Q_OUT;

  // ports of submodule bram_serverAdapter_outData_beforeEnq
  wire bram_serverAdapter_outData_beforeEnq$D_IN,
       bram_serverAdapter_outData_beforeEnq$EN,
       bram_serverAdapter_outData_beforeEnq$Q_OUT;

  // ports of submodule bram_serverAdapter_outData_ff
  wire [7 : 0] bram_serverAdapter_outData_ff$D_IN,
	       bram_serverAdapter_outData_ff$D_OUT;
  wire bram_serverAdapter_outData_ff$CLR,
       bram_serverAdapter_outData_ff$DEQ,
       bram_serverAdapter_outData_ff$EMPTY_N,
       bram_serverAdapter_outData_ff$ENQ,
       bram_serverAdapter_outData_ff$FULL_N;

  // rule scheduling signals
  wire WILL_FIRE_RL_init_bram, WILL_FIRE_RL_read_back;

  // inputs to muxes for submodule ports
  wire [7 : 0] MUX_bram_memory$put_2__VAL_1;

  // remaining internal signals
  wire [2 : 0] bram_serverAdapter_cnt_6_PLUS_IF_bram_serverAd_ETC___d22;
  wire bram_serverAdapter_cnt_6_SLT_3___d49;

  // value method get_read_data
  assign get_read_data = result ;
  assign RDY_get_read_data = 1'd1 ;

  // submodule bram_memory
  BRAM1 #(.PIPELINED(1'd0),
	  .ADDR_WIDTH(32'd8),
	  .DATA_WIDTH(32'd8),
	  .MEMSIZE(9'd256)) bram_memory(.CLK(CLK),
					.ADDR(bram_memory$ADDR),
					.DI(bram_memory$DI),
					.WE(bram_memory$WE),
					.EN(bram_memory$EN),
					.DO(bram_memory$DO));

  // submodule bram_serverAdapter_outData_beforeDeq
  RevertReg #(.width(32'd1),
	      .init(1'd1)) bram_serverAdapter_outData_beforeDeq(.CLK(CLK),
								.D_IN(bram_serverAdapter_outData_beforeDeq$D_IN),
								.EN(bram_serverAdapter_outData_beforeDeq$EN),
								.Q_OUT(bram_serverAdapter_outData_beforeDeq$Q_OUT));

  // submodule bram_serverAdapter_outData_beforeEnq
  RevertReg #(.width(32'd1),
	      .init(1'd1)) bram_serverAdapter_outData_beforeEnq(.CLK(CLK),
								.D_IN(bram_serverAdapter_outData_beforeEnq$D_IN),
								.EN(bram_serverAdapter_outData_beforeEnq$EN),
								.Q_OUT(bram_serverAdapter_outData_beforeEnq$Q_OUT));

  // submodule bram_serverAdapter_outData_ff
  SizedFIFO #(.p1width(32'd8),
	      .p2depth(32'd3),
	      .p3cntr_width(32'd1),
	      .guarded(1'd0)) bram_serverAdapter_outData_ff(.RST(RST_N),
							    .CLK(CLK),
							    .D_IN(bram_serverAdapter_outData_ff$D_IN),
							    .ENQ(bram_serverAdapter_outData_ff$ENQ),
							    .DEQ(bram_serverAdapter_outData_ff$DEQ),
							    .CLR(bram_serverAdapter_outData_ff$CLR),
							    .D_OUT(bram_serverAdapter_outData_ff$D_OUT),
							    .FULL_N(bram_serverAdapter_outData_ff$FULL_N),
							    .EMPTY_N(bram_serverAdapter_outData_ff$EMPTY_N));

  // rule RL_init_bram
  assign WILL_FIRE_RL_init_bram =
	     bram_serverAdapter_cnt_6_SLT_3___d49 && !inited ;

  // rule RL_read_back
  assign WILL_FIRE_RL_read_back =
	     bram_serverAdapter_outData_beforeDeq$Q_OUT &&
	     (bram_serverAdapter_outData_ff$EMPTY_N ||
	      bram_serverAdapter_outData_enqw$whas) &&
	     bram_serverAdapter_cnt_6_SLT_3___d49 &&
	     inited ;

  // inputs to muxes for submodule ports
  assign MUX_bram_memory$put_2__VAL_1 = addr - 8'd1 ;

  // inlined wires
  assign bram_serverAdapter_outData_enqw$whas =
	     bram_serverAdapter_outData_ff$FULL_N &&
	     bram_serverAdapter_s1[1] &&
	     bram_serverAdapter_s1[0] ;
  assign bram_serverAdapter_cnt_1$whas =
	     (WILL_FIRE_RL_read_back || WILL_FIRE_RL_init_bram) &&
	     (!bram_serverAdapter_writeWithResp$wget[1] ||
	      bram_serverAdapter_writeWithResp$wget[0]) ;
  assign bram_serverAdapter_writeWithResp$wget =
	     WILL_FIRE_RL_read_back ? 2'd0 : 2'd2 ;
  assign bram_serverAdapter_writeWithResp$whas =
	     WILL_FIRE_RL_read_back || WILL_FIRE_RL_init_bram ;
  assign bram_serverAdapter_s1_1$wget =
	     { 1'd1,
	       !bram_serverAdapter_writeWithResp$wget[1] ||
	       bram_serverAdapter_writeWithResp$wget[0] } ;

  // register addr
  assign addr$D_IN = addr + 8'd1 ;
  assign addr$EN = WILL_FIRE_RL_init_bram ;

  // register bram_serverAdapter_cnt
  assign bram_serverAdapter_cnt$D_IN =
	     bram_serverAdapter_cnt_6_PLUS_IF_bram_serverAd_ETC___d22 ;
  assign bram_serverAdapter_cnt$EN =
	     bram_serverAdapter_cnt_1$whas || WILL_FIRE_RL_read_back ;

  // register bram_serverAdapter_s1
  assign bram_serverAdapter_s1$D_IN =
	     bram_serverAdapter_writeWithResp$whas ?
	       bram_serverAdapter_s1_1$wget :
	       2'd0 ;
  assign bram_serverAdapter_s1$EN = 1'd1 ;

  // register data
  assign data$D_IN = data + 8'd1 ;
  assign data$EN = WILL_FIRE_RL_init_bram ;

  // register inited
  assign inited$D_IN = 1'd1 ;
  assign inited$EN = WILL_FIRE_RL_init_bram && addr == 8'd255 ;

  // register result
  assign result$D_IN =
	     bram_serverAdapter_outData_ff$EMPTY_N ?
	       bram_serverAdapter_outData_ff$D_OUT :
	       bram_memory$DO ;
  assign result$EN = WILL_FIRE_RL_read_back ;

  // submodule bram_memory
  assign bram_memory$ADDR =
	     WILL_FIRE_RL_read_back ? MUX_bram_memory$put_2__VAL_1 : addr ;
  assign bram_memory$DI =
	     WILL_FIRE_RL_read_back ?
	       8'b10101010 /* unspecified value */  :
	       data ;
  assign bram_memory$WE = !WILL_FIRE_RL_read_back ;
  assign bram_memory$EN = bram_serverAdapter_writeWithResp$whas ;

  // submodule bram_serverAdapter_outData_beforeDeq
  assign bram_serverAdapter_outData_beforeDeq$D_IN = 1'd1 ;
  assign bram_serverAdapter_outData_beforeDeq$EN = WILL_FIRE_RL_read_back ;

  // submodule bram_serverAdapter_outData_beforeEnq
  assign bram_serverAdapter_outData_beforeEnq$D_IN = 1'd1 ;
  assign bram_serverAdapter_outData_beforeEnq$EN =
	     bram_serverAdapter_outData_enqw$whas ;

  // submodule bram_serverAdapter_outData_ff
  assign bram_serverAdapter_outData_ff$D_IN = bram_memory$DO ;
  assign bram_serverAdapter_outData_ff$ENQ =
	     bram_serverAdapter_outData_enqw$whas &&
	     (!WILL_FIRE_RL_read_back ||
	      bram_serverAdapter_outData_ff$EMPTY_N) ;
  assign bram_serverAdapter_outData_ff$DEQ =
	     WILL_FIRE_RL_read_back && bram_serverAdapter_outData_ff$EMPTY_N ;
  assign bram_serverAdapter_outData_ff$CLR = 1'b0 ;

  // remaining internal signals
  assign bram_serverAdapter_cnt_6_PLUS_IF_bram_serverAd_ETC___d22 =
	     bram_serverAdapter_cnt +
	     (bram_serverAdapter_cnt_1$whas ? 3'd1 : 3'd0) +
	     (WILL_FIRE_RL_read_back ? 3'd7 : 3'd0) ;
  assign bram_serverAdapter_cnt_6_SLT_3___d49 =
	     (bram_serverAdapter_cnt ^ 3'h4) < 3'd7 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        addr <= `BSV_ASSIGNMENT_DELAY 8'd0;
	bram_serverAdapter_cnt <= `BSV_ASSIGNMENT_DELAY 3'd0;
	bram_serverAdapter_s1 <= `BSV_ASSIGNMENT_DELAY 2'd0;
	data <= `BSV_ASSIGNMENT_DELAY 8'd0;
	inited <= `BSV_ASSIGNMENT_DELAY 1'd0;
	result <= `BSV_ASSIGNMENT_DELAY 8'd0;
      end
    else
      begin
        if (addr$EN) addr <= `BSV_ASSIGNMENT_DELAY addr$D_IN;
	if (bram_serverAdapter_cnt$EN)
	  bram_serverAdapter_cnt <= `BSV_ASSIGNMENT_DELAY
	      bram_serverAdapter_cnt$D_IN;
	if (bram_serverAdapter_s1$EN)
	  bram_serverAdapter_s1 <= `BSV_ASSIGNMENT_DELAY
	      bram_serverAdapter_s1$D_IN;
	if (data$EN) data <= `BSV_ASSIGNMENT_DELAY data$D_IN;
	if (inited$EN) inited <= `BSV_ASSIGNMENT_DELAY inited$D_IN;
	if (result$EN) result <= `BSV_ASSIGNMENT_DELAY result$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    addr = 8'hAA;
    bram_serverAdapter_cnt = 3'h2;
    bram_serverAdapter_s1 = 2'h2;
    data = 8'hAA;
    inited = 1'h0;
    result = 8'hAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (bram_serverAdapter_s1[1] &&
	  (!bram_serverAdapter_outData_beforeEnq$Q_OUT ||
	   !bram_serverAdapter_outData_beforeDeq$Q_OUT ||
	   !bram_serverAdapter_outData_ff$FULL_N))
	$display("ERROR: %m: mkBRAMAdapter overrun");
  end
  // synopsys translate_on
endmodule  // mkTrapBram1

