//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e)
//
// On Sat Jul 18 12:00:03 CST 2026
//
//
// Ports:
// Name                         I/O  size props
// get_rx_data                    O     8 reg
// RDY_get_rx_data                O     1 const
// get_busy                       O     1 reg
// RDY_get_busy                   O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTrapSpi1(CLK,
		  RST_N,

		  get_rx_data,
		  RDY_get_rx_data,

		  get_busy,
		  RDY_get_busy);
  input  CLK;
  input  RST_N;

  // value method get_rx_data
  output [7 : 0] get_rx_data;
  output RDY_get_rx_data;

  // value method get_busy
  output get_busy;
  output RDY_get_busy;

  // signals for module outputs
  wire [7 : 0] get_rx_data;
  wire RDY_get_busy, RDY_get_rx_data, get_busy;

  // register bit_cnt
  reg [2 : 0] bit_cnt;
  wire [2 : 0] bit_cnt$D_IN;
  wire bit_cnt$EN;

  // register busy
  reg busy;
  wire busy$D_IN, busy$EN;

  // register cmd_reg
  reg [7 : 0] cmd_reg;
  wire [7 : 0] cmd_reg$D_IN;
  wire cmd_reg$EN;

  // register rx_buf
  reg [7 : 0] rx_buf;
  wire [7 : 0] rx_buf$D_IN;
  wire rx_buf$EN;

  // register shift_reg
  reg [7 : 0] shift_reg;
  wire [7 : 0] shift_reg$D_IN;
  wire shift_reg$EN;

  // value method get_rx_data
  assign get_rx_data = rx_buf ;
  assign RDY_get_rx_data = 1'd1 ;

  // value method get_busy
  assign get_busy = busy ;
  assign RDY_get_busy = 1'd1 ;

  // register bit_cnt
  assign bit_cnt$D_IN = bit_cnt + 3'd1 ;
  assign bit_cnt$EN = busy && bit_cnt != 3'd7 ;

  // register busy
  assign busy$D_IN = 1'd0 ;
  assign busy$EN = busy && bit_cnt == 3'd7 ;

  // register cmd_reg
  assign cmd_reg$D_IN = 8'h0 ;
  assign cmd_reg$EN = 1'b0 ;

  // register rx_buf
  assign rx_buf$D_IN = shift_reg ;
  assign rx_buf$EN = busy && bit_cnt == 3'd7 ;

  // register shift_reg
  assign shift_reg$D_IN = { shift_reg[6:0], 1'd0 } ;
  assign shift_reg$EN = busy && bit_cnt != 3'd7 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        bit_cnt <= `BSV_ASSIGNMENT_DELAY 3'd0;
	busy <= `BSV_ASSIGNMENT_DELAY 1'd0;
	cmd_reg <= `BSV_ASSIGNMENT_DELAY 8'h0;
	rx_buf <= `BSV_ASSIGNMENT_DELAY 8'h0;
	shift_reg <= `BSV_ASSIGNMENT_DELAY 8'h0;
      end
    else
      begin
        if (bit_cnt$EN) bit_cnt <= `BSV_ASSIGNMENT_DELAY bit_cnt$D_IN;
	if (busy$EN) busy <= `BSV_ASSIGNMENT_DELAY busy$D_IN;
	if (cmd_reg$EN) cmd_reg <= `BSV_ASSIGNMENT_DELAY cmd_reg$D_IN;
	if (rx_buf$EN) rx_buf <= `BSV_ASSIGNMENT_DELAY rx_buf$D_IN;
	if (shift_reg$EN) shift_reg <= `BSV_ASSIGNMENT_DELAY shift_reg$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    bit_cnt = 3'h2;
    busy = 1'h0;
    cmd_reg = 8'hAA;
    rx_buf = 8'hAA;
    shift_reg = 8'hAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkTrapSpi1

