//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e)
//
// On Sat Jul 18 11:59:41 CST 2026
//
//
// Ports:
// Name                         I/O  size props
// get_state                      O     2 reg
// RDY_get_state                  O     1 const
// get_data                       O     8
// RDY_get_data                   O     1 const
// is_active                      O     1
// RDY_is_active                  O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTrapFsm2(CLK,
		  RST_N,

		  get_state,
		  RDY_get_state,

		  get_data,
		  RDY_get_data,

		  is_active,
		  RDY_is_active);
  input  CLK;
  input  RST_N;

  // value method get_state
  output [1 : 0] get_state;
  output RDY_get_state;

  // value method get_data
  output [7 : 0] get_data;
  output RDY_get_data;

  // value method is_active
  output is_active;
  output RDY_is_active;

  // signals for module outputs
  reg [7 : 0] get_data;
  wire [1 : 0] get_state;
  wire RDY_get_data, RDY_get_state, RDY_is_active, is_active;

  // register count
  reg [3 : 0] count;
  wire [3 : 0] count$D_IN;
  wire count$EN;

  // register data
  reg [7 : 0] data;
  wire [7 : 0] data$D_IN;
  wire data$EN;

  // register state
  reg [1 : 0] state;
  wire [1 : 0] state$D_IN;
  wire state$EN;

  // value method get_state
  assign get_state = state ;
  assign RDY_get_state = 1'd1 ;

  // value method get_data
  always@(state or data)
  begin
    case (state)
      2'd0, 2'd3: get_data = 8'd0;
      2'd1: get_data = data;
      2'd2: get_data = 8'hFF;
    endcase
  end
  assign RDY_get_data = 1'd1 ;

  // value method is_active
  assign is_active = state == 2'd1 ;
  assign RDY_is_active = 1'd1 ;

  // register count
  assign count$D_IN = count + 4'd1 ;
  assign count$EN = state == 2'd1 && count < 4'd10 ;

  // register data
  assign data$D_IN = data + 8'd1 ;
  assign data$EN = state == 2'd1 && count < 4'd10 ;

  // register state
  assign state$D_IN = 2'd2 ;
  assign state$EN = state == 2'd1 && count < 4'd10 && count == 4'd9 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        count <= `BSV_ASSIGNMENT_DELAY 4'd0;
	data <= `BSV_ASSIGNMENT_DELAY 8'd0;
	state <= `BSV_ASSIGNMENT_DELAY 2'd0;
      end
    else
      begin
        if (count$EN) count <= `BSV_ASSIGNMENT_DELAY count$D_IN;
	if (data$EN) data <= `BSV_ASSIGNMENT_DELAY data$D_IN;
	if (state$EN) state <= `BSV_ASSIGNMENT_DELAY state$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    count = 4'hA;
    data = 8'hAA;
    state = 2'h2;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkTrapFsm2

