//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e)
//
// On Sat Jul 18 12:00:01 CST 2026
//
//
// Ports:
// Name                         I/O  size props
// get_irq                        O     8
// RDY_get_irq                    O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTrapInterrupt2(CLK,
			RST_N,

			get_irq,
			RDY_get_irq);
  input  CLK;
  input  RST_N;

  // value method get_irq
  output [7 : 0] get_irq;
  output RDY_get_irq;

  // signals for module outputs
  wire [7 : 0] get_irq;
  wire RDY_get_irq;

  // register mask
  reg [7 : 0] mask;
  wire [7 : 0] mask$D_IN;
  wire mask$EN;

  // register pending
  reg [7 : 0] pending;
  wire [7 : 0] pending$D_IN;
  wire pending$EN;

  // register source
  reg [7 : 0] source;
  wire [7 : 0] source$D_IN;
  wire source$EN;

  // value method get_irq
  assign get_irq = pending & mask ;
  assign RDY_get_irq = 1'd1 ;

  // register mask
  assign mask$D_IN = 8'h0 ;
  assign mask$EN = 1'b0 ;

  // register pending
  assign pending$D_IN = source ;
  assign pending$EN = 1'b1 ;

  // register source
  assign source$D_IN = source + 8'd1 ;
  assign source$EN = 1'd1 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        mask <= `BSV_ASSIGNMENT_DELAY 8'hFF;
	pending <= `BSV_ASSIGNMENT_DELAY 8'd0;
	source <= `BSV_ASSIGNMENT_DELAY 8'd0;
      end
    else
      begin
        if (mask$EN) mask <= `BSV_ASSIGNMENT_DELAY mask$D_IN;
	if (pending$EN) pending <= `BSV_ASSIGNMENT_DELAY pending$D_IN;
	if (source$EN) source <= `BSV_ASSIGNMENT_DELAY source$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    mask = 8'hAA;
    pending = 8'hAA;
    source = 8'hAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkTrapInterrupt2

