//
// Generated by Bluespec Compiler, version 2025.07 (build 282e82e)
//
// On Sat Jul 18 12:00:02 CST 2026
//
//
// Ports:
// Name                         I/O  size props
// get_done                       O     1 reg
// RDY_get_done                   O     1 const
// get_result                     O     8 reg
// RDY_get_result                 O     1 const
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTrapCrc2(CLK,
		  RST_N,

		  get_done,
		  RDY_get_done,

		  get_result,
		  RDY_get_result);
  input  CLK;
  input  RST_N;

  // value method get_done
  output get_done;
  output RDY_get_done;

  // value method get_result
  output [7 : 0] get_result;
  output RDY_get_result;

  // signals for module outputs
  wire [7 : 0] get_result;
  wire RDY_get_done, RDY_get_result, get_done;

  // register cnt
  reg [3 : 0] cnt;
  wire [3 : 0] cnt$D_IN;
  wire cnt$EN;

  // register crc
  reg [7 : 0] crc;
  wire [7 : 0] crc$D_IN;
  wire crc$EN;

  // register data
  reg [7 : 0] data;
  wire [7 : 0] data$D_IN;
  wire data$EN;

  // register done
  reg done;
  wire done$D_IN, done$EN;

  // value method get_done
  assign get_done = done ;
  assign RDY_get_done = 1'd1 ;

  // value method get_result
  assign get_result = crc ;
  assign RDY_get_result = 1'd1 ;

  // register cnt
  assign cnt$D_IN = cnt + 4'd1 ;
  assign cnt$EN = cnt < 4'd8 ;

  // register crc
  assign crc$D_IN = crc ^ data ;
  assign crc$EN = cnt < 4'd8 ;

  // register data
  assign data$D_IN = 8'h0 ;
  assign data$EN = 1'b0 ;

  // register done
  assign done$D_IN = 1'd1 ;
  assign done$EN = cnt == 4'd8 ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        cnt <= `BSV_ASSIGNMENT_DELAY 4'd0;
	crc <= `BSV_ASSIGNMENT_DELAY 8'd0;
	data <= `BSV_ASSIGNMENT_DELAY 8'd0;
	done <= `BSV_ASSIGNMENT_DELAY 1'd0;
      end
    else
      begin
        if (cnt$EN) cnt <= `BSV_ASSIGNMENT_DELAY cnt$D_IN;
	if (crc$EN) crc <= `BSV_ASSIGNMENT_DELAY crc$D_IN;
	if (data$EN) data <= `BSV_ASSIGNMENT_DELAY data$D_IN;
	if (done$EN) done <= `BSV_ASSIGNMENT_DELAY done$D_IN;
      end
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    cnt = 4'hA;
    crc = 8'hAA;
    data = 8'hAA;
    done = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkTrapCrc2

